export const CATEGORIES_MAP = {
	PROSTATE: 'prostate',
	WOMB: 'womb',
	LUNGS: 'lungs',
	RESPIRATORY: 'respiratory',
	KIDNEY: 'kidney',
	KIDNEYS: 'kidneys',
	STOMACH: 'stomach',
	INTESTINES: 'intestines',
	INFLAMMATION: 'inflammation',
	ANTI_INFLAMMATORY: 'anti-inflammatory',
	ARTHRITIS: 'arthritis',
	BLOOD_PRESSURE: 'blood pressure',
	BLOOD_SUGAR: 'blood sugar',
	DIABETES: 'diabetes',
	CANCER: 'cancer',
	UTI: 'uti',
	ANTIBACTERIAL: 'antibacterial',
	ANTIFUNGAL: 'antifungal',
	ANTIVIRAL: 'antiviral',
	YEAST: 'yeast',
	PARASITES: 'parasites',
	WORMS: 'worms',
	BRAIN: 'brain',
	MEMORY: 'memory',
	STI: 'sti',
	CHOLESTEROL: 'cholesterol',
	BLOOD: 'blood',
	ANEMIA: 'anemia',
	IMMUNE_SYSTEM: 'immune system',
	SPRAIN: 'sprain',
	BONES: 'bones',
	CIRCULATION: 'circulation',
};

export const CATEGORIES_ARRAY = [
	{ display: 'Anemia', value: 'anemia', link: 'anemia', image: '/images/blood.png' },
	{
		display: 'Antibacterial',
		value: 'antibacterial',
		link: 'antibacterial',
		image: '',
	},
	{ display: 'Antifungal', value: 'antifungal', link: 'antifungal', image: '' },
	{ display: 'Antiviral', value: 'antiviral', link: 'antiviral', image: '' },
	{ display: 'Arthritis', value: 'arthritis', link: 'arthritis', image: '' },
	{ display: 'Blood', value: 'blood', link: 'blood', image: '/images/blood.png' },
	{
		display: 'Blood Pressure',
		value: 'blood pressure',
		link: 'blood-pressure',
		image: '/images/blood.png',
	},
	{
		display: 'Blood Sugar',
		value: 'blood sugar',
		link: 'blood-sugar',
		image: '/images/blood.png'
	},
	{ display: 'Bones', value: 'bones', link: 'bones', image: '' },
	{ display: 'Brain', value: 'brain', link: 'brain', image: '' },
	{ display: 'Cancer', value: 'cancer', link: 'cancer', image: '' },
	{
		display: 'Cholesterol',
		value: 'cholesterol',
		link: 'cholesterol',
		image: '',
	},
	{
		display: 'Circulation',
		value: 'circulation',
		link: 'circulation',
		image: '/images/blood.png'
	},
	{ display: 'Diabetes', value: 'diabetes', link: 'diabetes', image: '' },
	{
		display: 'Immune System',
		value: 'immune system',
		link: 'immune-system',
		image: '',
	},
	{
		display: 'Inflammation',
		value: 'inflammation',
		link: 'inflammation',
		image: '',
	},
	{ display: 'Intestines', value: 'intestines', link: 'intestines', image: '' },
	{ display: 'Kidneys', value: 'kidneys', link: 'kidneys', image: '' },
	{ display: 'Lungs', value: 'lungs', link: 'lungs', image: '' },
	{ display: 'Memory', value: 'memory', link: 'memory', image: '' },
	{ display: 'Parasites', value: 'parasites', link: 'parasites', image: '' },
	{ display: 'Prostate', value: 'prostate', link: 'prostate', image: '' },
	{
		display: 'Respiratory',
		value: 'respiratory',
		link: 'respiratory',
		image: '',
	},
	{ display: 'Sprain', value: 'sprain', link: 'sprain', image: '' },
	{ display: 'Sti', value: 'sti', link: 'sti', image: '' },
	{ display: 'Stomach', value: 'stomach', link: 'stomach', image: '' },
	{ display: 'Uti', value: 'uti', link: 'uti', image: '' },
	{ display: 'Womb', value: 'womb', link: 'womb', image: '' },
	{ display: 'Yeast', value: 'yeast', link: 'yeast', image: '' },
];

export const HEADER_LINKS = [
	{
		label: 'Plants',
		link: '/plants',
	},
	{
		label: 'Benefits',
		link: '/benefits',
	},
	{
		label: 'About Us',
		link: '/about',
	},
];

export const REGION_NAMES = {
	northAmerica: 'North America',
	southAmerica: 'South America',
	centralAmerica: 'Central America',
	caribbean: 'Caribbean',
};
